//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VooPPointMgr.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vooEntities : DbContext
    {
        public vooEntities()
            : base("name=vooEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<channel> channels { get; set; }
        public DbSet<tchannel_ppoint> tchannel_ppoint { get; set; }
        public DbSet<tdevicechannelaccess> tdevicechannelaccesses { get; set; }
        public DbSet<tencoderdevice> tencoderdevices { get; set; }
        public DbSet<tppoint> tppoints { get; set; }
        public DbSet<tppointstatu> tppointstatus { get; set; }
    }
}
