//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VooPPointMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tchannel_ppoint
    {
        public int ID_CHANNEL { get; set; }
        public int ID_PPOINT { get; set; }
        public int ID_STATUS { get; set; }
    
        public virtual tppointstatu tppointstatu { get; set; }
    }
}
