//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VooPPointMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tppointstatu
    {
        public tppointstatu()
        {
            this.tchannel_ppoint = new HashSet<tchannel_ppoint>();
        }
    
        public int ID_STATUS { get; set; }
        public string PPOINT_STATUS { get; set; }
    
        public virtual ICollection<tchannel_ppoint> tchannel_ppoint { get; set; }
    }
}
