//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VooPPointMgr.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdevicechannelaccess
    {
        public int ID_DEVICE { get; set; }
        public int ID_CHANNEL { get; set; }
    }
}
