//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VooPPointMgr.DataL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tppoint
    {
        public int ID_PPOINT { get; set; }
        public string IIS_NAME { get; set; }
        public string URL { get; set; }
        public string AMS_URL { get; set; }
        public string AMS_PREVIEW { get; set; }
        public string AMS_PLAYER { get; set; }
        public bool IN_USE { get; set; }
    }
}
